- name: 尝试推送离线 metallb镜像（若执行失败，可忽略）
  copy: src={{ base_dir }}/down/{{ metallb_offline }} dest=/opt/kube/images/{{ metallb_offline }}
  when: 'metallb_offline in download_info.stdout'

- name: 获取metallb离线镜像推送情况
  command: "ls /opt/kube/images"
  register: image_info

- name: 导入 metallb的离线镜像（若执行失败，可忽略）
  shell: "{{ bin_dir }}/docker load -i /opt/kube/images/{{ metallb_offline }}"
  when: 'metallb_offline in image_info.stdout and CONTAINER_RUNTIME == "docker"'

- name: 导入 metallb的离线镜像（若执行失败，可忽略）
  shell: "{{ bin_dir }}/ctr -n=k8s.io images import /opt/kube/images/{{ metallb_offline }}"
  when: 'metallb_offline in image_info.stdout and CONTAINER_RUNTIME == "containerd"'

- name: 生成 metallb 相关 manifests
  template: src=metallb/{{ item }}.j2 dest=/opt/kube/kube-system/{{ item }}
  with_items:
  - "metallb.yaml"
  - "{{ metallb_protocol }}.yaml"

- name: 创建 metallb controller 部署
  shell: "{{ bin_dir }}/kubectl apply -f /opt/kube/kube-system/metallb.yaml && \
          {{ bin_dir }}/kubectl apply -f /opt/kube/kube-system/{{ metallb_protocol }}.yaml"
